### PR TITLE
fixed directory permissions

### LINKED ISSUE #1: permission issues
FYI @erasche  . . found when testing here:

https://github.com/TAMU-CPT/galaxy-apollo/issues/2

```
Fatal error: Exit code 1 ()
cp: cannot create directory ‘/apollo-data/6’: Permission denied
INFO:__main__:Determining if add or update required
INFO:__main__:  Adding Organism
INFO:__main__:Updating permissions for <User 19: Bob Jones <admin@galaxy.org>>
```

The default permissions were: `drwxr-xr-x   2 root   root   4096 May 28 16:19 apollo-data`

Did a:

chmod -R 777 /apollo-data

locally and it fixed it.

Not sure if the fix goes here or in the image file directly.

### PR DESCRIPTION
**Pull request by nathandunn**
@erasche  This fixed #1 for me, but you can let me know if I did it the correct way.

### CODE REVIEW

**Comment by hexylena** [comment]
@nathandunn that fixes it? That should prevent apollo from even launching, as command will override the default command.

**Comment by nathandunn** [comment]
Let me try it with a rebuild . . . maybe I won't be so lucky

**Comment by nathandunn** [comment]
Are you talking about this line:

https://github.com/GMOD/docker-compose-galaxy-annotation/pull/2/files#diff-4e5e90c6228fd48698d074241c2ba760R33

or the following one:

https://github.com/GMOD/docker-compose-galaxy-annotation/pull/2/files#diff-4e5e90c6228fd48698d074241c2ba760R34

I'll retry with a clean build.

**Comment by hexylena** [comment]
Overriding the command. (You shouldn't need to rebuild, a kill / up should suffice to see the effects)

**Comment by nathandunn** [comment]
Alright . . I’ll try that . . 

Isn’t the /apollo-data one of the galaxy volumes?  So it should be mounted as rw (even if the others are not)?

**Comment by hexylena** [comment]
yeah, the /apollo-data volume comes from galaxy (the rationale being that apollo can refer to paths from anywhere, there is no reason to hardcode a specific folder on the apollo side).

It should be mounted rw, as that's the default (i.e. no `:ro` after the volumes_from in the apollo section)

**Comment by hexylena** [comment]
Oh! Wow! I'm just seeing this now, how could I be so blind. You're right, the `:rw` is absolutely needed, see if it works without the `command` block.

**Comment by nathandunn** [comment]
Will do.

**Comment by nathandunn** [comment]
Hmm . . so I did change it to ":rw" . . unfortunately the permissions don't change and root:root ≠ galaxy:galaxy and so it fails. 

For giggles I tried the command block and it did as you thought .. i.e., it just up and died.   Any other ideas?

**Comment by hexylena** [comment]
On second thought, the `:rw` isn't needed, apollo never writes back to the JBrowse dir, so that should've been fine. I'll see what I can do about adding a cron script or something.

**Comment by nathandunn** [comment]
i wonder if the postinst is run as a non-root user?

**Comment by hexylena** [comment]
Postinst wasn't used anymore and was removed from Apollo. It ran as root to move the directory around. We need to fix it from the Galaxy side unfortunately.

**Comment by nathandunn** [comment]
ahh . . dang . . . should I close this then?

**Comment by hexylena** [comment]
Nah, leave it open. I'll poke the galaxy image tonight

**Comment by hexylena** [comment]
Should have been fixed in https://github.com/erasche/docker-galaxy-annotation/commit/a33105d252e00e0538328b3b32ff17c7567cbf6b

**Pull request closed without merging**
